### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Pinkan** [lejara/Da-Twitch-Charades#62]
You could do in another language aswell. I'm brazilian and could do the translation to portuguese-br, including some brazilian youtube, tv shows, and everything. Thank you :)

**Comment by lejara** [comment]
Good Idea!

While it is a nice thing to have. This can add more work as it stands right now.
Not only it has to be translated, but also have to add in the code for it, and going forward it needs to be updated with any future updates.

Since I am the only one mostly working on this, it might be too much.
Maybe in the future it can be possible.

The website recently got updated, which allows you to add in your own words. So you can use that for the time being.

Thx for posting an idea! <3
